import React from 'react'
import { ShieldAlert } from 'lucide-react'

export default function LegalDisclaimer() {
  return (
    <div className="mt-6 bg-slate-800/50 border border-slate-700 rounded-lg p-4">
      <div className="flex items-start gap-2">
        <ShieldAlert size={16} className="text-yellow-500 mt-0.5 shrink-0" />
        <p className="text-xs text-slate-400">
          <span className="font-semibold text-yellow-500">Educational Use Only:</span> All analyses, scores, verdicts, and estimates generated by this software are algorithmic approximations for informational purposes only. They do not constitute financial, legal, investment, or real estate advice. Always verify ARV with licensed appraisers and recent MLS comps. Consult licensed attorneys for legal issues. Never rely solely on this software for any real estate transaction. Track DealOS and its developers assume no liability for decisions made based on this analysis.
        </p>
      </div>
    </div>
  )
}
