import React, { useState, useEffect } from 'react'
import { AlertTriangle } from 'lucide-react'

export default function TermsModal() {
  const [show, setShow] = useState(false)

  useEffect(() => {
    const accepted = localStorage.getItem('terms_accepted')
    if (!accepted) setShow(true)
  }, [])

  function handleAccept() {
    localStorage.setItem('terms_accepted', '1')
    setShow(false)
  }

  if (!show) return null

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-4">
      <div className="bg-slate-800 border border-slate-700 rounded-xl max-w-2xl w-full max-h-[90vh] flex flex-col shadow-2xl">
        <div className="flex items-center gap-3 px-6 py-4 border-b border-slate-700">
          <AlertTriangle className="text-yellow-400 shrink-0" size={22} />
          <h2 className="text-lg font-bold text-white">Terms of Use & Legal Disclaimer</h2>
        </div>
        <div className="overflow-y-auto flex-1 px-6 py-4 text-sm text-slate-300 space-y-4">
          <p className="font-semibold text-yellow-400 text-base">IMPORTANT: READ BEFORE USING THIS SOFTWARE</p>
          <p>Track DealOS Property Analyzer ("the Software") is provided for <strong>educational and informational purposes only</strong>. Nothing in this application constitutes financial, legal, tax, investment, or real estate advice.</p>
          <p>All property analyses, scores, verdicts, valuations, repair estimates, and strategy recommendations generated by this Software are automated algorithmic estimates based on user-entered data. They are <strong>not guaranteed to be accurate</strong> and should not be relied upon as the sole basis for any real estate transaction or investment decision.</p>
          <p><strong>By using this Software, you acknowledge and agree:</strong></p>
          <ul className="list-disc pl-5 space-y-2">
            <li>You are a real estate professional or sophisticated investor with experience evaluating property deals independently.</li>
            <li>All analyses must be independently verified with licensed appraisers, title companies, attorneys, and qualified inspectors before proceeding with any transaction.</li>
            <li>The AI-generated verdicts and scores may be incorrect, incomplete, or based on inaccurate data. Always verify ARV with licensed appraisers and recent MLS comps.</li>
            <li>Repair estimates are rough approximations only. Hire licensed contractors for actual estimates before any purchase.</li>
            <li>Legal issues including bankruptcy, IRS liens, title defects, and foreclosure proceedings require consultation with a licensed attorney. This Software does not provide legal advice.</li>
            <li>You will not hold Track DealOS, its developers, or affiliates liable for any financial loss or damages resulting from use of this Software.</li>
            <li>Web search results and AI analysis may be outdated, incorrect, or incomplete. Market conditions change rapidly.</li>
            <li>Past performance estimates do not guarantee future results.</li>
          </ul>
          <p className="text-slate-400 text-xs mt-4">By clicking "I Accept," you confirm you have read, understood, and agree to these terms. If you do not agree, do not use this Software.</p>
        </div>
        <div className="px-6 py-4 border-t border-slate-700">
          <button
            onClick={handleAccept}
            className="w-full bg-blue-600 hover:bg-blue-700 text-white font-semibold py-3 rounded-lg transition-colors"
          >
            I Accept — Enter Track DealOS
          </button>
        </div>
      </div>
    </div>
  )
}
